// <auto-generated />
using System;
using EFCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Migrations.InheritanceDb
{
    [DbContext(typeof(InheritanceDbContext))]
    [Migration("20260627160335_TPT")]
    partial class TPT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EFCore.Models.FullTime", b =>
                {
                    b.HasBaseType("EFCore.Models.Person");

                    b.Property<DateOnly>("HiringDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("FullTime", (string)null);
                });

            modelBuilder.Entity("EFCore.Models.PartTime", b =>
                {
                    b.HasBaseType("EFCore.Models.Person");

                    b.Property<decimal>("HourRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoursCount")
                        .HasColumnType("int");

                    b.ToTable("PartTime", (string)null);
                });

            modelBuilder.Entity("EFCore.Models.FullTime", b =>
                {
                    b.HasOne("EFCore.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("EFCore.Models.FullTime", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.Models.PartTime", b =>
                {
                    b.HasOne("EFCore.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("EFCore.Models.PartTime", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
